### ISSUE TITLE
虾米音乐失效&七牛未认证账号的支持？

### ISSUE THREAD

**Issue by cdiscrete** [naoyeye/Perber#18]
试图在Perber.com上发虾米，似乎不行了。

然后七牛未认证账号的网址结构似乎和认证账号是不一样的，考虑添加支持？

**Comment by naoyeye** [comment]
@cdiscrete 专门用来解析虾米音乐地址的服务器被我停掉了，因为用的人太少。

你说的「网址结构」指的是什么？

**Comment by cdiscrete** [comment]
@naoyeye 就是比如说我的qiniu网址是7abcde.abc1.z0.glb.clouddn.com 这样的。

能否自己架设一个虾米音乐的解析地址？

**Comment by naoyeye** [comment]
@cdiscrete 可以的。我单独把虾米音乐解析服务拿出来了，在这里：

https://github.com/naoyeye/xiamiRun

你可以在本地跑一下试试（README 里给出的示例地址已经失效了）：

clone 代码到本地之后，安装需要的包，然后输入 sails lift 运行起来，浏览器中输入

http://127.0.0.1:1337/xiami/run?song={虾米的歌曲页面 url} 就会返回相应的

{
    title: "xxx",
    artist: "xxx",
    album: "x",
    url: "xxx",
    cover: "xxx"
}

不过不知道后来虾米有没有改算法。

没问题的话在服务器上跑着就可以。

**Comment by cdiscrete** [comment]
我看到那个项目了，我还以为是整合起来的。

Ok，那我如何修改Perber来使用我自己的解析服务器呢？

**Comment by naoyeye** [comment]
https://github.com/naoyeye/Perber/blob/master/perber/sockets.js#L459

把这一行的地址换成自己的就可以了。当时随便写的，没来得及在 config.json 中做处理。
